### ISSUE TITLE
W/System.err( 5254): android.content.res.Resources$NotFoundException: String resource ID #0x0

### ISSUE THREAD

**Issue by WangShayne** [fluttercandies/flutter_qweather#6]
您好,我在按照example示例,插入自己的项目时候,提示这个错误

我把您的项目下载后运行example,也是提示这个错误. 我是flutter新手,我觉得可能是我环境的问题,但我不能确定这个问题出在哪里,您是否能指点一下解决思路呢?

```
Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 2,419ms.
I/flutter ( 5254): 和风天气：初始化结果: true
W/Settings( 5254): Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.
I/flutter ( 5254): Instance of 'Future<WarningRsp?>'
E/example.home_v( 5254): Invalid ID 0x00000000.
W/System.err( 5254): android.content.res.Resources$NotFoundException: String resource ID #0x0
W/System.err( 5254): 	at android.content.res.Resources.getText(Resources.java:444)
W/System.err( 5254): 	at android.content.res.Resources.getString(Resources.java:537)
W/System.err( 5254): 	at com.qweather.sdk.c.a.g(DeviceUtil.java:321)
W/System.err( 5254): 	at com.qweather.sdk.c.a.d(DeviceUtil.java:211)
W/System.err( 5254): 	at com.qweather.sdk.b.c.a(BaseData.java:84)
W/System.err( 5254): 	at com.qweather.sdk.b.l.a(WarningDataImpl.java:37)
W/System.err( 5254): 	at com.qweather.sdk.view.QWeather.getWarning(QWeather.java:831)
W/System.err( 5254): 	at com.qweather.sdk.view.QWeather.getWarning(QWeather.java:821)
W/System.err( 5254): 	at com.fluttercandies.flutter_qweather.ApiWarning.getWarning(ApiWarning.java:35)
W/System.err( 5254): 	at com.fluttercandies.flutter_qweather.FlutterQweatherPlugin.onMethodCall(FlutterQweatherPlugin.kt:37)
W/System.err( 5254): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
W/System.err( 5254): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/System.err( 5254): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
W/System.err( 5254): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
W/System.err( 5254): 	at android.os.Handler.handleCallback(Handler.java:938)
W/System.err( 5254): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err( 5254): 	at android.os.Looper.loop(Looper.java:223)
W/System.err( 5254): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
W/System.err( 5254): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 5254): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
W/System.err( 5254): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

flutter doctor -v

```
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [版本 10.0.19041.572], locale zh-CN)
    • Flutter version 3.0.5 at D:\Program Files\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (4 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at D:\Program Files\Android\SDK
    • Platform android-33, build-tools 33.0.0
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.5)
    • Visual Studio at D:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32616.157
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.69.2)
    • VS Code at C:\Users\shayne\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1
    • NO_PROXY contains localhost
    ! NO_PROXY does not contain ::1
    • NO_PROXY contains 127.0.0.1

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [版本 10.0.19041.572]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 104.0.5112.79

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

**Comment by CyJaySong** [comment]
这是SDK自身的问题😂

**Comment by WangShayne** [comment]
@CyJaySong 请问您说的SDK是什么,我切换到Android 4.4的SDK还是报这个错误

**Comment by CyJaySong** [comment]
@WangShayne 插件里面集成了和风天气的SDK, SDK报的错误，这个需要和风团队修复才行
